### ISSUE TITLE
Server Config Generator Suggestions

### ISSUE THREAD

**Issue by ToddButler93** [Gigabyte5671/wilderzone-live#1]
# Server Config Suggestions

## Weapon Modifications
- [ ] Allow Weapons to have their value mods and changes added to the config.
- [ ] Create a file/folder structure similar to the GOTY Preset for OOTB weapon modifications.
- [ ] Allow for users to use GOTY or OOTB as a base.
- [ ] Add functionality to download multi-file configs (basic container like .zip).

## Seed Data
- [ ] Add a seed for config values.
- [ ] Save seed to config as a comment when downloading config.
- [ ] Loading config data from seed on webpage.

**Comment by Gigabyte5671** [comment]
Starting to work on a new layout and database concept. Will be working to accommodate all of these suggestions. Updates will follow in this thread.

**Comment by Gigabyte5671** [comment]
Closing this issue. See [Llamagrab](https://llamagrab.net/) for running and maintaining community servers.
